### PR TITLE
New checkout of the wpt submodule - run `git submodule update`

### PR DESCRIPTION
**Pull request by orottier**
Contains https://github.com/web-platform-tests/wpt/pull/44749 and https://github.com/web-platform-tests/wpt/pull/44783

### CODE REVIEW

**Comment by orottier** [comment]
```
  RESULTS:
  - # pass: 5016
  - # fail: 658
  - # type error issues: 54

**Comment by b-ma** [comment]
Cool!

**Comment by orottier** [comment]
Hmmm, try `git submodule sync --recursive`  ?

**Comment by b-ma** [comment]
Thanks, the command output didn't tell much but seems the .gitmodule points to the right place

```sh
/node-web-audio-api [main] $ cat .gitmodules
[submodule "wpt"]
	path = wpt
	url = git@github.com:web-platform-tests/wpt.git
```

Let's hope this is ok

**Pull request merged**
